### ISSUE TITLE
Exception when viewing the email in Admin

### ISSUE THREAD

**Issue by brad** [zapier/django-drip#19]
I think this must have broken with the changes in #18, because the `build_email` method was removed there.

AttributeError at /orcas/admin/drip/drip/2/timeline/4/7/911/

'DripBase' object has no attribute 'build_email'

Request Method:     GET
Request URL:    http://127.0.0.1:8000/orcas/admin/drip/drip/2/timeline/4/7/911/
Django Version:     1.4.2
Exception Type:     AttributeError
Exception Value:    

'DripBase' object has no attribute 'build_email'

Exception Location:     /home/bpitcher/.virtualenvs/jauntly/src/django-drip/drip/admin.py in view_drip_email, line 56
